version: '2'

services:
  phonebook-mysql:
    container_name: phonebook-mysql
    image: cheisr/opsschool_project/app
    ports:
      - "3306:3306"
    restart: always

  phonebook-app:
    container_name: phonebook-app
    image: cheisr/opsschool_project/mysql
    depends_on:
      - phonebook-mysql
    ports:
      - "8181:8181"
    restart: always
