apiVersion: v1
kind: Service
metadata:
  name: project-service
  labels:
    app: project-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: project-app
