apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: project-app
  template:
    metadata:
      labels:
        app: project-app
    spec:
     containers:
     - name: project-app
       image: cheisr/opsschool_project_app:latest
       resources: {}
       ports:
       - containerPort: 8181
       env:
       - name: MYSQL_ADDRESS
         valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql_host
       - name: MYSQL_USER
         valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql_user
       - name: MYSQL_PWD
         valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql_pass
