apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: project-app
  template:
    metadata:
      labels:
        app: project-app
    spec:
     containers:
     - name: project-app
       image: cheisr/opsschool_project:latest
       resources:
         requests:
           memory: "64Mi"
           cpu: "250m"
         limits:
          memory: "128Mi"
          cpu: "500m"
       ports:
       - containerPort: 8181
       env:
       - name: MYSQL_ADDRESS
         valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql_host    
       - name: MYSQL_USER
         valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql_user
       - name: MYSQL_PWD
         valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql_pass