
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: project-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: project-app
  template:
    metadata:
      labels:
        app: project-app
    spec:
     containers:
     - name: project-app
       image: cheisr/opsschool_project_app:latest
       resources:
         requests:
           memory: "64Mi"
           cpu: "250m"
         limits:
          memory: "128Mi"
          cpu: "500m"
       ports:
       - containerPort: 8181
       env:
       - name: MYSQL_ADDRESS
         valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql_host
       - name: MYSQL_USER
         valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql_user
       - name: MYSQL_PWD
         valueFrom:
            configMapKeyRef:
                name: mysql-config
                key: mysql_pass
     - name: project-mysql
       image: cheisr/opsschool_project_mysql:latest
       resources: {}
       ports:
         - containerPort: 3306
           name: mysql
       volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
     volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
       
